### ISSUE TITLE
Proposal: TCG expansion codes and abbreviations

### ISSUE THREAD

**Issue by immewnity** [Pokemon-Standards-Consortium/standards#4]
## Overview
- Scope: TCG releases by Wizards of the Coast, Nintendo, Pokémon USA, and/or The Pokémon Company International
- Desired outcome: Ability to uniquely identify each expansion using a common format

## Background
There has been some confusion around set codes/abbreviations, which is making it really complicated to easily allow use of the Compendium's new API (which allows for rulings to be pulled by card) for various projects. Some examples:
* RK9 Labs uses TK10A to refer to the Alolan Raichu deck, while the Pokémon TCG Online uses TK10A to refer to the Lycanroc deck.
* The Pokémon TCG Online uses TK6A and TK6B to refer to the Noibat & Sylveon Trainer Kit, while the PokeGym Researching Tower uses TK5 to refer to these.
* The PokeGym Researching Tower uses TR to refer to the Team Rocket expansion, PkmnCards uses TR to refer to the EX Team Rocket Returns expansion.

**Comment by MatiasOETamminen** [comment]
I am compiling a sheet of all the abbreviations used around the web: https://docs.google.com/spreadsheets/d/1K-3za6S_fY9EvjICUmHU7f9bx6955XctDNNNYrIskDo/

**Comment by immewnity** [comment]
Given the additional interest, I'll take that as seconding the initiative - PSC 001 has been created for this project.
